# -*- coding: utf-8 -*-
"""Task-2  CREDIT CARD FRAUD DETECTION.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jeSi7UMNcetpocs7O1jNlbGaVJ5YcIM7
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,f1_score

df=pd.read_csv("creditcard.csv")

df.head()

df.shape

df.isnull().sum()

df.describe()

df["Class"]==1

df["Class"].value_counts()

df.dtypes